plugins {
  id 'java-library'
}

group = 'com.boardly'
version = '0.0.1-SNAPSHOT'

java {
  toolchain { languageVersion = JavaLanguageVersion.of(libs.versions.java.get()) }
}

repositories { mavenCentral() }

dependencies {
  api project(':boardly-shared')
  implementation libs.spring.boot.starter.web
  implementation libs.spring.boot.starter.security
  implementation libs.bundles.springdoc.dependencies
  // MapStruct for API DTO <-> Domain mapping
  implementation libs.mapstruct
  annotationProcessor libs.mapstruct.processor

  compileOnly libs.lombok
  annotationProcessor libs.lombok

  testImplementation libs.spring.boot.starter.test
}

tasks.named('test') { useJUnitPlatform() }
