package com.boardly.features.activity.domain.model;

public enum ActivityType {
    // 카드 관련
    CARD_CREATE,
    CARD_MOVE,
    CARD_RENAME,
    CARD_ARCHIVE,
    CARD_DELETE,
    CARD_ASSIGN_MEMBER,
    CARD_UNASSIGN_MEMBER,
    CARD_SET_DUE_DATE,
    CARD_ADD_COMMENT,
    CARD_ADD_ATTACHMENT,
    CARD_ADD_CHECKLIST,
    CARD_DUPLICATE,
    CARD_UPDATE_DESCRIPTION,

    // 리스트 관련
    LIST_CREATE,
    LIST_RENAME,
    LIST_ARCHIVE,
    LIST_MOVE,
    LIST_CHANGE_COLOR,
    LIST_DELETE,

    // 보드 관련
    BOARD_CREATE,
    BOARD_RENAME,
    BOARD_ARCHIVE,
    BOARD_UNARCHIVE,
    BOARD_MOVE,
    BOARD_DELETE,
    BOARD_UPDATE_DESCRIPTION,
    BOARD_ADD_MEMBER,
    BOARD_REMOVE_MEMBER,
    BOARD_UPDATE_MEMBER_ROLE,
    BOARD_DUPLICATE,

    // 사용자 관련
    USER_UPDATE_PROFILE,
    USER_CHANGE_LANGUAGE,
    USER_CHANGE_PASSWORD,
    USER_DELETE_ACCOUNT
}
