plugins {
    id 'java-library'
}

java {
  toolchain { languageVersion = JavaLanguageVersion.of(libs.versions.java.get()) }
}

repositories { mavenCentral() }

dependencies {
    // Internal modules
    implementation project(':boardly-shared')
    
    // Lombok
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    
    // Validation
    implementation libs.validation.api
    
    // Test
    testImplementation libs.junit.jupiter
    testImplementation libs.mockito.core
    testImplementation libs.assertj.core
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
