[versions]
# Java
java = "21"

# Spring Boot
spring-boot = "3.4.1"
spring-dependency-management = "1.1.7"

# Database
h2 = "2.3.232"
postgres = "42.7.8"

# Lombok
lombok = "1.18.38"
lombok-mapstruct-binding = "0.2.0"

# JPA & QueryDSL
querydsl = "5.0.0:jakarta"

# Test
junit-jupiter = "5.11.4"
mockito = "5.14.2"
testcontainers = "1.20.4"

# Logging
logback = "1.5.12"

# Validation
validation = "3.1.0"

# Security
spring-security = "6.4.2"

# Web
spring-web = "6.2.1"

# JSON
jackson = "2.18.2"

# Documentation
springdoc-openapi = "2.8.9"

# Monitoring
actuator = "3.4.1"

# Database Migration
flyway = "11.1.1"

# MapStruct
mapstruct = "1.6.3"

# Vavr
vavr = "0.10.7"

# ULID
ulid-creator = "5.2.3"

[libraries]
# Spring Boot
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

# Database
h2 = { module = "com.h2database:h2", version.ref = "h2" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }

# JPA & QueryDSL
querydsl-apt = { module = "com.querydsl:querydsl-apt", version.ref = "querydsl" }
querydsl-jpa = { module = "com.querydsl:querydsl-jpa", version.ref = "querydsl" }

# Test
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

# Logging
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Validation
validation-api = { module = "jakarta.validation:jakarta.validation-api", version.ref = "validation" }

# Security
spring-security-test = { module = "org.springframework.security:spring-security-test" }

# Web
spring-web = { module = "org.springframework:spring-web", version.ref = "spring-web" }

# JSON
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

# Documentation
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi" }

# Monitoring
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }

# Database Migration
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

# Lombok
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# MapStruct
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

# Vavr
vavr = { module = "io.vavr:vavr", version.ref = "vavr" }

# ULID
ulid-creator = { module = "com.github.f4b6a3:ulid-creator", version.ref = "ulid-creator" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
querydsl = { id = "com.ewerk.gradle.plugins.querydsl", version = "1.0.10" }

[bundles]
spring-boot-starter = [
    "spring-boot-starter",
    "spring-boot-starter-web",
    "spring-boot-starter-data-jpa",
    "spring-boot-starter-validation",
]
spring-boot-test = ["spring-boot-starter-test", "spring-security-test"]
testcontainers = ["testcontainers-junit-jupiter", "testcontainers-postgresql"]
