plugins {
  id 'boardly.spring-boot-conventions'
}

dependencies {
  api project(':boardly-shared')
  implementation project(':boardly-domain')
  implementation libs.bundles.spring.boot.dependencies
  // Flyway dependencies removed; migrations now live in :boardly-schema
  implementation libs.bundles.springdoc.dependencies
  // MapStruct for mapping between domain <-> entity and domain <-> dto
  implementation libs.mapstruct
  annotationProcessor libs.mapstruct.processor
  runtimeOnly libs.postgres
}
