package com.boardly.domain.activitylog;

/**
 * 활동 타입
 * 국제화를 위해 enum 값만 정의하고, 표시 이름은 메시지 키로 처리
 */
public enum ActivityType {
    // 보드 관련 활동
    BOARD_CREATED,
    BOARD_UPDATED,
    BOARD_DELETED,
    BOARD_ARCHIVED,
    BOARD_RESTORED,

    // 카드 관련 활동
    CARD_CREATED,
    CARD_UPDATED,
    CARD_DELETED,
    CARD_MOVED,
    CARD_ASSIGNED,
    CARD_UNASSIGNED,

    // 컬럼 관련 활동
    COLUMN_CREATED,
    COLUMN_UPDATED,
    COLUMN_DELETED,
    COLUMN_REORDERED,

    // 댓글 관련 활동
    COMMENT_ADDED,
    COMMENT_UPDATED,
    COMMENT_DELETED,

    // 체크리스트 관련 활동
    CHECKLIST_CREATED,
    CHECKLIST_UPDATED,
    CHECKLIST_DELETED,
    CHECKLIST_ITEM_COMPLETED,
    CHECKLIST_ITEM_UNCOMPLETED,

    // 라벨 관련 활동
    LABEL_CREATED,
    LABEL_UPDATED,
    LABEL_DELETED,
    LABEL_ADDED_TO_CARD,
    LABEL_REMOVED_FROM_CARD,

    // 워크스페이스 관련 활동
    WORKSPACE_CREATED,
    WORKSPACE_UPDATED,
    WORKSPACE_DELETED,
    MEMBER_JOINED,
    MEMBER_LEFT,
    MEMBER_ROLE_CHANGED,

    // 초대 관련 활동
    INVITATION_SENT,
    INVITATION_ACCEPTED,
    INVITATION_DECLINED,
    INVITATION_EXPIRED;
}
