spring:
  datasource:
    name: boardly-app
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/boardly}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:boardly}
    password: ${SPRING_DATASOURCE_PASSWORD:boardly123}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        '[format_sql]': ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:false}
        jdbc:
          '[time_zone]': UTC
  flyway:
    enabled: true
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/local
  security:
    oauth2:
      authorizationserver:
        client:
          boardly-client:
            registration:
              client-id: "boardly-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "${app.frontend.url}/callback"
              post-logout-redirect-uris:
                - "${app.frontend.url}/"
              scopes:
                - "openid"
                - "read"
                - "write"
            require-authorization-consent: false
            require-proof-key: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    oauth:
      client-id: "boardly-client"
      client-secret: "{noop}secret"
      scopes:
        - read
        - write
        - openid
      use-pkce-with-authorization-code-grant: true

app:
  cors:
    allowed-origins:
      - "${app.frontend.url}"
  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:5173}
    
boardly:
  card:
    policy:
      max-cards-per-list: 100
      max-title-length: 200
      max-description-length: 2000
      max-search-results: 50
  boardlist:
    policy:
      max-lists-per-board: 20
      recommended-lists-per-board: 10
      warning-threshold: 15
      max-title-length: 100
  attachment:
    policy:
      max-file-size-mb: 10
      max-attachments-per-card: 10
      max-file-name-length: 255

# 로깅 설정
logging:
  level:
    '[org.springframework.security]': info
    '[com.boardly]': info
    '[org.hibernate.SQL]': ${SPRING_JPA_SHOW_SQL:false}
    '[org.hibernate.type.descriptor.sql.BasicBinder]': ${SPRING_JPA_SHOW_SQL:false}

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always