plugins {
    id 'boardly.spring-boot-application-conventions'
    id 'jacoco'
    alias(libs.plugins.openapi.gradle.plugin)
}

dependencies {
    implementation project(':boardly-shared')
    implementation project(':boardly-api')
    implementation project(':boardly-infrastructure')
    implementation project(':boardly-domain')
    implementation project(':boardly-application')
  implementation project(':boardly-schema')

    implementation libs.bundles.spring.boot.dependencies
    implementation libs.bundles.common.dependencies

    // springdoc
    implementation(libs.bundles.springdoc.dependencies)

  // flyway
  implementation(libs.bundles.flyway.dependencies)

    // Lombok / MapStruct
    annotationProcessor(libs.lombok.mapstruct.binding)
    implementation(libs.mapstruct)
    annotationProcessor(libs.mapstruct.processor)

    testCompileOnly(libs.lombok)
    testAnnotationProcessor(libs.lombok)
    testAnnotationProcessor(libs.lombok.mapstruct.binding)

    // DB drivers
    runtimeOnly(libs.h2)
    runtimeOnly(libs.postgres)

    testImplementation libs.bundles.spring.test.dependencies
}

jacoco { toolVersion = libs.versions.jacoco.get() }

// OpenAPI 자동 생성 제거 (수동 태스크 및 연동 전부 삭제)
